lib/tilex_web/router.ex
defmodule TilexWeb.Router do
  use TilexWeb, :router

  @auth_controller Application.get_env(:tilex, :auth_controller)
  @cors_origin Application.get_env(:tilex, :cors_origin)

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(Tilex.Plug.BasicAuth)
    plug(Tilex.Plug.FormatInjector)
  end

  pipeline :browser_auth do
    plug(Guardian.Plug.VerifySession)
    plug(Guardian.Plug.LoadResource)
  end

  pipeline :api do
    if @cors_origin do
      plug(CORSPlug, origin: @cors_origin)
    end

    plug(:accepts, ["json"])
  end

  scope "/api", TilexWeb do
    pipe_through([:api])

    get("/developer_posts.json", Api.DeveloperPostController, :index)
  end

  get("/rss", TilexWeb.FeedController, :index)

  scope "/", TilexWeb do
    pipe_through([:browser, :browser_auth])

    get("/admin", @auth_controller, :index)
    delete("/auth/logout", AuthController, :delete)
    get("/auth/:provider", AuthController, :request)
    get("/auth/:provider/callback", AuthController, :callback)
    post("/auth/:provider/callback", AuthController, :callback)

    get("/statistics", StatsController, :index)

    get("/sitemap.xml", SitemapController, :index)
    get("/manifest.json", WebManifestController, :index)
    get("/random", PostController, :random)
    get("/:name", ChannelController, :show)
    get("/authors/:name", DeveloperController, :show)
    get("/profile/edit", DeveloperController, :edit)
    put("/profile/edit", DeveloperController, :update)

    get("/", PostController, :index)
    resources("/posts", PostController, param: "titled_slug")
    post("/posts/:slug/like.json", PostController, :like)
    post("/posts/:slug/unlike.json", PostController, :unlike)
  end
end

lib/tilex_web/controllers/feed_controller.ex
defmodule TilexWeb.FeedController do
  use TilexWeb, :controller

  def index(conn, _params) do
    posts = Repo.all from p in Tilex.Post,
      order_by: [desc: p.inserted_at],
      preload: [:developer],
      limit: 25

    conn
    |> put_resp_content_type("application/xml")
    |> render("index.xml", items: posts)
  end
end

lib/tilex_web/views/feed_view.ex
defmodule TilexWeb.FeedView do
  use TilexWeb, :view
end

lib/tilex_web/templates/feed/index.xml.eex
<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>Today I Learned</title>
    <description>TIL is an open-source project by Hashrocket that exists to catalogue the sharing and accumulation of knowledge as it happens day-to-day.
    </description>
    <link><%= post_url(@conn, :index) %></link>
    <atom:link href="<%= feed_url(@conn, :index) %>" rel="self" type="application/rss+xml" />
    <%= for post <- @items do %>
      <item>
        <title>
          <![CDATA[<%= post.title %>]]>
        </title>
        <link><%= post_url(@conn, :show, post) %></link>
        <description>
          <![CDATA[<%= Tilex.Markdown.to_html(post.body) %>]]>
        </description>
        <dc:creator>
          <%= post.developer.username %>
        </dc:creator>
        <pubDate><%= TilexWeb.SharedView.rss_date(post) %></pubDate>
        <guid isPermaLink="true"><%= post_url(@conn, :show, post) %></guid>
      </item>
    <% end %>
  </channel>
</rss>