lib/tilex_web/router.ex
defmodule TilexWeb.Router do
  use TilexWeb, :router

  @auth_controller Application.get_env(:tilex, :auth_controller)
  @cors_origin Application.get_env(:tilex, :cors_origin)

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(Tilex.Plug.BasicAuth)
    plug(Tilex.Plug.FormatInjector)
  end

  pipeline :browser_auth do
    plug(Guardian.Plug.VerifySession)
    plug(Guardian.Plug.LoadResource)
  end

  pipeline :api do
    if @cors_origin do
      plug(CORSPlug, origin: @cors_origin)
    end

    plug(:accepts, ["json"])
  end

  scope "/api", TilexWeb do
    pipe_through([:api])

    get("/developer_posts.json", Api.DeveloperPostController, :index)
  end

  get("/rss", TilexWeb.FeedController, :index)

  scope "/", TilexWeb do
    pipe_through([:browser, :browser_auth])

    get("/admin", @auth_controller, :index)
    delete("/auth/logout", AuthController, :delete)
    get("/auth/:provider", AuthController, :request)
    get("/auth/:provider/callback", AuthController, :callback)
    post("/auth/:provider/callback", AuthController, :callback)

    get("/statistics", StatsController, :index)

    get("/sitemap.xml", SitemapController, :index)
    get("/manifest.json", WebManifestController, :index)
    get("/random", PostController, :random)
    get("/:name", ChannelController, :show)
    get("/authors/:name", DeveloperController, :show)
    get("/profile/edit", DeveloperController, :edit)
    put("/profile/edit", DeveloperController, :update)

    get("/", PostController, :index)
    resources("/posts", PostController, param: "titled_slug")
    post("/posts/:slug/like.json", PostController, :like)
    post("/posts/:slug/unlike.json", PostController, :unlike)
  end
end

lib/tilex_web/views/shared_view.ex
defmodule TilexWeb.SharedView do
  use TilexWeb, :view

  def display_date(post) do
    Timex.format!(post.inserted_at, "%B %-e, %Y", :strftime)
  end

  def rss_date(post) do
    Timex.format!(post.inserted_at, "%a, %d %b %Y %H:%M:%S GMT", :strftime)
  end

  def pluralize(1, object), do: "1 #{object}"
  def pluralize(count, object), do: "#{count} #{object}s"

  def pagination_href(conn, page) do
    conn.request_path <> "?" <> URI.encode_query(Map.put(conn.params, "page", page))
  end
end

lib/tilex_web/templates/shared/_elixir.html.eex
Looking for help? Elixir is quickly gaining momentum for web applications that
need concurrency, performance, and the ability to connect to many different
clients. The developers at
<a href="https://hashrocket.com/elixir">Hashrocket</a>
are learning along with the rest of the development community that Elixir and
Phoenix are viable Rails alternatives for the right application.
Check out the
<a href="https://github.com/hashrocket/tilex">source code</a>
for Today I Learned, written in Elixir, and
<a href="https://hashrocket.com/contact-us">contact us</a>
if you need help with your Elixir project.

lib/tilex_web/templates/shared/_pagination.html.eex
<nav class="pagination">
  <%= if @page > 1 do %>
    <a rel="previous" class="pagination_newer" href="<%= pagination_href(@conn, @page - 1) %>">newer TILs</a>
  <% end %>

  <%= if Enum.count(@posts) > Application.get_env(:tilex, :page_size) do %>
    <a rel="next" class="pagination_older" href="<%= pagination_href(@conn, @page + 1)%>">older TILs</a>
  <% end %>
</nav>

lib/tilex_web/templates/shared/_posts_list.html.eex
<%= for post <- Enum.take(@posts, Application.get_env(:tilex, :page_size)) do %>
  <%= render TilexWeb.SharedView, "post.html", conn: @conn, post: post %>
<% end %>

lib/tilex_web/templates/shared/_rails.html.eex
Looking for help?
<a href="https://hashrocket.com/ruby-on-rails">Hashrocket</a>
has been an industry leader in Ruby on Rails since 2008. Rails is a core skill
for each developer at Hashrocket and we'd love to take a look at your project.
<a href="https://hashrocket.com/contact-us">Contact us</a>
and find out how we can help you.

lib/tilex_web/templates/shared/_ruby.html.eex
Looking for help? Each developer at
<a href="https://hashrocket.com">Hashrocket</a>
has years of experience working with Ruby applications of all types and sizes.
<a href="https://hashrocket.com/contact-us">Contact us</a>
and find out how we can help you.

lib/tilex_web/templates/shared/_sql.html.eex
Looking for help?
<a href="https://hashrocket.com">Hashrocket</a>
developers believe that data quality is as important as code quality. We enjoy
all the challenges of relational databases, from finding the fastest index, to
structuring data to fit the needs of an application. We're eager to share our
experiences; check out
<a href="https://www.pgcasts.com">PG Casts</a>,
a series of free weekly PostgreSQL screencasts.

lib/tilex_web/templates/shared/_vim.html.eex
Every developer at
<a href="https://hashrocket.com">Hashrocket</a>
is a Vim expert. Check out our development environment,
<a href="https://github.com/hashrocket/dotmatrix">Dotmatrix</a>,
and if you are in Chicago, come to the monthly
<a href="https://www.meetup.com/Vim-Chicago">Vim Chicago Meetup</a>
hosted at our Chicago office.

lib/tilex_web/templates/shared/post.html.eex
<section>
  <article class="post">
    <section>
      <div class="post__content copy">
        <h1>
          <%= link(@post.title, to: post_path(@conn, :show, @post)) %>
        </h1>
        <%= raw Tilex.Markdown.to_html(@post.body) %>

        <%= if assigns[:twitter_shareable] && Mix.env != :test do %>
          <a href='http://twitter.com/share'
             class='twitter-share-button'
             data-text= "Today I learned: <%= @post.title %>"
             data-via= "<%= Tilex.Developer.twitter_handle(@post.developer) %>"
             data-hashtags= "<%= @post.channel.twitter_hashtag %>"
             data-url= "<%= post_url(@conn, :show, @post) %>">
            Tweet
          </a>
        <% end %>

        <footer>
          <p>
            <%= link(@post.developer.username, to: developer_path(@conn, :show, @post.developer)) %>
            <br/>
            <%= link(display_date(@post), to: post_path(@conn, :show, @post), class: "post__permalink") %>
          </p>
        </footer>
      </div>
      <aside>
        <ul>
          <li>
            <%= link("##{@post.channel.name}", to: channel_path(@conn, :show, @post.channel.name), class: "post__tag-link") %>
          </li>
          <li>
            <%= link("permalink", to: post_path(@conn, :show, @post), class: "post__permalink") %>
          </li>
          <li>
            <%= link("raw", to: "#{post_path(@conn, :show, @post)}.md", class: "post__raw-link") %>
          </li>
          <%= if Guardian.Plug.current_resource(@conn) && (@post.developer == Guardian.Plug.current_resource(@conn) || Guardian.Plug.current_resource(@conn).admin) do %>
            <li>
              <%= link("edit", to: post_path(@conn, :edit, @post), class: "post__permalink") %>
            </li>
          <% end %>
          <li>
            <%= link to: "#", class: "js-like-action post__like-link", id: @post.slug do %>
              <span class="post__like-count"><%= @post.likes %></span>
              <span class="post__like-label">likes</span>
            <% end %>
          </li>
        </ul>
      </aside>
    </section>
  </article>
</section>